### ISSUE TITLE
Spark requirement version looks out of date?

### ISSUE THREAD

**Issue by djacobs7** [ash-project/ash_paper_trail#2]
Hi,

I was trying to get this package working, and it looks like maybe it's locked to an ancient version of spark?  I ended up forking the project, and removing the dependency ( because, in my particular case, I have ash installed, which already has spark as a dependency ). 

Not sure what the right path forward is - or if you are even still supporting this code - but wanted to make you aware.  Thanks for the nice software!

**Comment by zachdaniel** [comment]
This should be fixed in main now. Mind giving it a shot?

**Comment by djacobs7** [comment]
Tried it out, looks good, thanks!
