### ISSUE TITLE
Changes attribute should be sensitive

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash_paper_trail#22]
Since the changes attribute could include sensitive attributes, it should itself be sensitive.

Should it also be private?

**Comment by zachdaniel** [comment]
Hmm...probably *all* attributes should be private, except for explicitly configured public ones?

**Comment by zachdaniel** [comment]
And yes they should be similarly sensitive

**Comment by rgraff** [comment]
The `attributes_as_attributes` copy their sensitive and private options. I think that's good for now.
