### ISSUE TITLE
Error with GraphQL models

### ISSUE THREAD

**Issue by djacobs7** [ash-project/ash_paper_trail#3]
I am having some issues with using ash_papertrail and on a model that uses GraphQL.  I copied the example from the README, and this is the issue I am seeing

The following code gives me this error: 

== Compilation error in file lib/myapp/myapi/resources/sample.ex ==
** (Spark.Error.DslError) [MyApp.Sample]
 Multiple values for key `:action`
    deps/ash_paper_trail/lib/resource/transformers/create_version_resource.ex:157: anonymous fn/4 in :elixir_compiler_10.__MODULE__/1
    (elixir 1.15.4) lib/keyword.ex:1048: Keyword.do_merge/6
    deps/ash_paper_trail/lib/resource/transformers/create_version_resource.ex:157: (module)
    (spark 1.1.22) .../resources/sample.ex:20: Spark.Dsl.__before_compile__/1

If I remove the mixin, I get this error:

** (Absinthe.Schema.Error) Compilation failed:
---------------------------------------
## Locations
/Users/danieljacobs/git/api/deps/ash_graphql/lib/resource/resource.ex:2326

In field Paper_trail_versions, :_filter_input is not defined in your schema.

Types must exist if referenced.

`
defmodule MyApp.Sample.PaperTrailMixin do

  defmacro __using__(_) do
    quote do
      graphql do
        type :sample_versions

        queries do
          list :list_versions, action: :read
        end
      end

    end
  end
end

defmodule MyApp.Sample do
  use Scribble.Resource,
    api: MyApp,
    extensions: [AshGraphql.Resource, AshPaperTrail.Resource],
    authorizers: [Ash.Policy.Authorizer]

    attributes do
      uuid_primary_key :id
      attribute :name, :uuid, allow_nil?: false
      create_timestamp :inserted_at
      update_timestamp :updated_at
    end

    graphql do
      type :sample
    end

    paper_trail do
      mixin MyApp.Sample.PaperTrailMixin

      version_extensions extensions: [AshGraphql.Resource]

    end
  actions do
    defaults [:read]
  end

end
`

Does this look familiar?

**Comment by zachdaniel** [comment]
So the first error is the `list` call should look like this:
```elixir
      list :list_versions, :read
```

The second is *usually* what happens when there is a resource somewhere that uses the ash graphql extension but doesn't define a type. Could that be the case for one of your resources?

**Comment by djacobs7** [comment]
Ok - I fixed  this

      list :list_versions, :read

and now it works without complaining . The other error was only happening when I removed GraphQL from the mixin - and as it happens, I need graphQL, so I am going to not worry about it for now and will investigrate further if it comes up.




HOWEVER - now I run into this issue when I try to actually do a write.  Any ideas?

`[error] GenServer #PID<0.1341.0> terminating
** (Ash.Error.Invalid) Context: resolving data on perform MyApp.MyAPI.Sample.create

Input Invalid

* No such attribute inserted_at for resource Scribble.Scribe.Sample.Version
    (ash 2.14.0) lib/ash/api/api.ex:2167: Ash.Api.unwrap_or_raise!/3
    (ash_paper_trail 0.1.0) lib/resource/changes/create_new_version.ex:75: anonymous fn/2 in AshPaperTrail.Resource.Changes.CreateNewVersion.create_new_version/1
    (ash 2.14.0) lib/ash/changeset/changeset.ex:2149: anonymous fn/2 in Ash.Changeset.run_after_actions/3
    (elixir 1.15.4) lib/enum.ex:4830: Enumerable.List.reduce/3
    (elixir 1.15.4) lib/enum.ex:2564: Enum.reduce_while/3
    (ash 2.14.0) lib/ash/changeset/changeset.ex:1854: anonymous fn/2 in Ash.Changeset.transaction_hooks/2
    (ash 2.14.0) lib/ash/changeset/changeset.ex:1775: Ash.Changeset.with_hooks/3
    (ash 2.14.0) lib/ash/actions/create/create.ex:328: anonymous fn/11 in Ash.Actions.Create.as_requests/5
    (ash 2.14.0) lib/ash/engine/request.ex:1111: Ash.Engine.Request.do_try_resolve_local/4
    (ash 2.14.0) lib/ash/engine/request.ex:284: Ash.Engine.Request.do_next/1
    (ash 2.14.0) lib/ash/engine/request.ex:213: Ash.Engine.Request.next/1
    (ash 2.14.0) lib/ash/engine/engine.ex:712: Ash.Engine.advance_request/2
    (ash 2.14.0) lib/ash/engine/engine.ex:637: Ash.Engine.fully_advance_request/2
    (ash 2.14.0) lib/ash/engine/engine.ex:578: Ash.Engine.do_run_iteration/2
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ash 2.14.0) lib/ash/engine/engine.ex:307: Ash.Engine.run_to_completion/1
    (ash 2.14.0) lib/ash/engine/engine.ex:252: Ash.Engine.do_run/2
    (ash 2.14.0) lib/ash/engine/engine.ex:148: Ash.Engine.run/2
    (ash 2.14.0) lib/ash/actions/create/create.ex:99: Ash.Actions.Create.do_run/4
    (ash 2.14.0) lib/ash/actions/create/create.ex:38: Ash.Actions.Create.run/4`

**Comment by zachdaniel** [comment]
Just pushed something to main, if you want to give it a shot :)

**Comment by djacobs7** [comment]
That fixed that problem, we are getting there!  Here is the next issue
 
I have my resources backed by postgres, and its complaining that tables don't exist. I am trying to run `ash_postgres.generate_migrations` but it's not working.  See code below:


```

[nix-shell:~/git/api]$ mix ash_postgres.generate_migrations --name add_samples_and_version
Compiling 9 files (.ex)

Generated MyApp app
** (ArgumentError) `nil` is not a Spark DSL module.

    nil.spark_dsl_config()
    (spark 1.1.22) lib/spark/dsl/extension.ex:135: Spark.Dsl.Extension.dsl!/1
    (spark 1.1.22) lib/spark/dsl/extension.ex:153: Spark.Dsl.Extension.get_entities/2
    (ash 2.14.0) lib/ash/resource/info.ex:575: Ash.Resource.Info.attribute/2
    (ash_postgres 1.3.40) lib/migration_generator/migration_generator.ex:2622: anonymous fn/4 in AshPostgres.MigrationGenerator.find_reference/3
    (elixir 1.15.4) lib/enum.ex:4307: Enum.find_value_list/3
    (ash_postgres 1.3.40) lib/migration_generator/migration_generator.ex:2612: anonymous fn/3 in AshPostgres.MigrationGenerator.attributes/2
    (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2

```

```

defmodule MyApp.MyApi.Sample.PaperTrailMixin do

  defmacro __using__(_) do
    quote do
      graphql do
        type :sample_versions

        queries do
          list :list_versions,  :read
        end
      end



    end
  end
end

defmodule MyApp.MyApi.Sample do
  use Scribble.Resource,
    api: MyApp.MyApi,
    data_layer: AshPostgres.DataLayer,

    extensions: [AshGraphql.Resource, AshPaperTrail.Resource],
    authorizers: [Ash.Policy.Authorizer]



    attributes do
      uuid_primary_key :id
      attribute :name, :string, allow_nil?: false
      create_timestamp :inserted_at
      update_timestamp :updated_at
    end

    graphql do
      type :sample
    end

    paper_trail do
      mixin MyApp.MyApi.Sample.PaperTrailMixin

      version_extensions extensions: [AshGraphql.Resource]

    end

  actions do
    defaults [:read,  :update, :create]


  end

  postgres do
    table "samples"
    repo Scribble.Repo

  end

end


```

**Comment by zachdaniel** [comment]
Ah, yes, interesting...I think you'll need to put the generated resource into your api/ registry. Are you using a registry? If not you can switch to a registry and then there is a registry extension in this repo to add version resources.

**Comment by djacobs7** [comment]
I am using a registry, but maybe I didn't add the extension correctly? Is this what you mean?

```
defmodule Scribble.Scribe.Registry do
  use Ash.Registry,
    extensions: [Ash.Registry.ResourceValidations,
    AshPaperTrail.Registry
  ]

  entries do
    entry MyApp.MyAPI.Sample
    entry MyApp.MyAPI.Sample.Version. # add this line
  end
end

```

**Comment by zachdaniel** [comment]
🤔 you shouldn't need to add that line, as the registry extension should do it. Not sure where this is going wrong. If you could push up a reproduction repo, I'm sure I can get to the bottom of it. Hopefully this is the last roadblock, sorry its been rocky, this package is still a bit experimental.

**Comment by djacobs7** [comment]
Ok I think I have a repro. I modified the test to use the Postgres data layer instead of ets ( and put in a littl ebit of configuration so that we could connect to postgres) , and that was basically enough to reproduce the bug.

https://github.com/djacobs7/ash_paper_trail/tree/bug__postgres_data_layer

Then, just run these steps:
    MIX_ENV=test mix ecto.create
    MIX_ENV=test mix ash_postgres.generate_migrations

**Comment by zachdaniel** [comment]
Should be fixed now :)
