### ISSUE TITLE
belongs_to_actor relationship must be public

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash_paper_trail#47]
In Ash Paper Trail v0.1.2-rc.0, the `belongs_to_actor` option will not work if the relationship is not public.

**Additional context**
Ash 3.0.0-rc.21

**Comment by zachdaniel** [comment]
Ah, so we need to make that `attribute_writable? true` in that case then.

**Comment by zachdaniel** [comment]
wait, that already is happening... 🤔

**Comment by zachdaniel** [comment]
What error does it raise?

**Comment by rgraff** [comment]
In my use case, the relationship can be nil and it always was.  When I make the relationship public, it was being set correctly.

**Comment by zachdaniel** [comment]
When you get some time could you push a failing test for this? I haven't been able to figure out why this would happen.

**Comment by zachdaniel** [comment]
When you get some time could you push a failing test for this? I haven't been able to figure out why this would happen, and haven't had time to reproduce either.

**Comment by nallwhy** [comment]
I can handle this issue.

**Comment by nallwhy** [comment]
I think this is related to https://github.com/ash-project/ash/pull/1053.
If `default_accept :*` is a backwards compatibility tool, ash extensions shouldn't use that. It's not all attributes, but **public** all attributes.

**Comment by nallwhy** [comment]
I think It can be fixed with a transformer that creates actions accepting all attributes.
What do you think?

**Comment by zachdaniel** [comment]
You're correct about the problem, good call. I would say we can do this w/o a transformer. get all attributes in the transformer that we're in, and then add `accept unquote(all_attributes)` to the actions we create.
