### ISSUE TITLE
Optionally associate the change with the actor

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash_paper_trail#7]
Request for feedback: I'd like to associated each version with the actor making the change. 

The most straightforward approach IMHO would be to create an :actor relationship and manage it automatically. The syntax could be:

```elixir
paper_trail do
  belongs_to_actor Users.User, api: Users, allow_nil?: false
end
```

An alternative approach would follow the builtin change relate_actor and leave relationship itself to be added via mixin.

```elixir
paper_trail do
  relate_actor :relationship, allow_nil?: false, field: :id
end
```

**Comment by frankdugan3** [comment]
Tracking the actor is super important for my use cases, but I have the added complication of the actor being multiple different things. For example, it could be a `User`, `Employee`, or `Workcenter`. As long as the actor is an Ash resource, perhaps another option would be to track that with something like `actor: {resource, id}`?

**Comment by zachdaniel** [comment]
🤔 I don't think that we should store the resource itself...but there would need to be some way to express what it is. We could use the `Ash.Resource.Info.short_name`

**Comment by rgraff** [comment]
I have the same need to with multiple possible actor modules.

My idea is to allow multiple `belongs_to_actor` for each type. So the
version would have an employee_id and a contractor_id for example.

**Comment by rgraff** [comment]
Good first issue? 😓

**Comment by zachdaniel** [comment]
😅good first issue doesn't necessarily mean "easy". What it means is that it is relatively isolated in impact from core functionality, could potentially be a learning opportunity, and isn't necessary urgent on its own.

**Comment by zachdaniel** [comment]
Also when you made it I didn’t know at the time you’d be putting all of the work in shortly afterward so I wanted to encourage people to try it out :)

**Comment by rgraff** [comment]
It was harder than I thought but a good learning experience, so maybe it was a good first issue after all. 😄
